name: Setup Script Test

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
    # 以下のファイルに変更があれば実行される。
    paths:
      - 'setup.sh'
      - '*.sh'
      - '.github/workflows/**'
jobs:
  test-setup:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libncursesw5-dev sudo

      - name: Compile
        run: make

      - name: Test 1
        run: ldd setup_tool

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: setup_tool_linux_amd64
          path: setup_tool
