name: Setup Script Test

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
    # 以下のファイルに変更があれば実行される。
    paths:
      - 'setup_ui.cpp'
      - '*.sh'
      - '.github/workflows/**'

permissions:
  contents: write

jobs:
  test-setup:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential libncursesw5-dev sudo

      - name: Compile
        run: make

      - name: check glibc version
        run: ldd --version

      - name: Test 1
        run: ldd setup_tool

      - name: Run test
        run: chmod +x setup_tool && ./setup_tool --all
     
      - name: Release binary
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: latest
          name: Latest Build
          files: setup_tool
          draft: false
          prerelease: false
